In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5,2)), range(5)

In [2]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
list(y)

[0, 1, 2, 3, 4]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)
X_train

array([[4, 5],
       [6, 7],
       [0, 1]])

In [6]:
y_train

[2, 3, 0]

In [7]:
X_test

array([[8, 9],
       [2, 3]])

In [8]:
y_test

[4, 1]

now train/fit our model on the training data

model.fit(X_train,y_train)

predictions = model.predict(X_test)

We can evaluate our model by comparing our predictions to the correct values. (Depends on what Machine Learning Algorithm is used.)

supervised estimetors:

- model.predict()
- model.predict_proba()
- model.score()

unsupervised estimetors:

- model.predict()
- model.transform()
- model.fit_transform()