NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.83894321, 0.26676796, 0.16162619, 0.80917875, 0.35135671])

In [23]:
np.random.rand(5,5)

array([[0.14324325, 0.40247382, 0.81151078, 0.08435438, 0.52917354],
       [0.66379389, 0.72609314, 0.09435096, 0.39835477, 0.38711524],
       [0.84533395, 0.10060825, 0.01310432, 0.99020788, 0.57607981],
       [0.73598801, 0.95429467, 0.81993687, 0.4130868 , 0.75732486],
       [0.98897985, 0.99502365, 0.92047479, 0.28487784, 0.51311124]])

In [25]:
np.random.randn(4)

array([-0.3616094 ,  1.14291551,  0.92743022, -0.73586512])

In [26]:
np.random.randn(4,2)

array([[ 0.35770728, -1.01800489],
       [ 0.51602923, -0.54862437],
       [ 0.03062034, -0.04015801],
       [-0.31944701, -0.82615862]])

In [27]:
np.random.randint(1,100)

69

In [28]:
np.random.randint(1,100,6)

array([27, 17, 52, 60, 62, 86], dtype=int32)

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([23, 38, 16, 22, 29, 28, 41, 36,  4,  6], dtype=int32)

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

NumPy Indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[5]

np.int64(5)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

?????? changes the original array too, it's no a copy, but a view
NumPy does that to avoid memory issues with verry large arrays

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:] = 100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Matrixes

In [26]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]

np.int64(5)

In [29]:
arr_2d[2,1]

np.int64(40)

In [ ]:
# take 0 and 1 lines
# and all columns after 1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [35]:
arr_2d[1:,0:2]

array([[20, 25],
       [35, 40]])

In [36]:
arr = np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
bool_array = arr > 5

In [41]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[~(arr>5)]

array([1, 2, 3, 4, 5])

NumPy Operations

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [52]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [53]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [54]:
1/0

ZeroDivisionError: division by zero

In [55]:
arr / arr

C:\Users\menez\AppData\Local\Temp\ipykernel_18276\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [56]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [57]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [58]:
np.max(arr)

np.int64(10)

In [59]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [60]:
np.log(arr)

C:\Users\menez\AppData\Local\Temp\ipykernel_18276\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

https://numpy.org/doc/2.2/reference/ufuncs.html